"""
Django settings for ARPBIGIDISBA_frontend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_m-1mo5%058umv#@eyi28m5p%(k^z&-#w7gz&&m53i$55sqogs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Debe ir antes de 'django.contrib.admin'
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # External Apps
    'django_tables2',
    'crispy_forms',
    'crispy_bootstrap4',
    'crispy_bootstrap5',
    'django_bootstrap5',
    'bootstrap4',
    'bootstrap5',
    'advanced_filters',
    'django_filters',
    'django_tables2_column_shifter',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'channels',
    'import_export', # Necesario para que Dash funcione con Django

    # Project Apps
    'home',
    'dashboard',
    'upload',
    'apps',
    'bank',
]
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap5.html"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'home.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',
]

ROOT_URLCONF = 'ARPBIGIDISBA_frontend.urls'

APPEND_SLASH=True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.user_role', # Context processor personalizado para roles de usuario
            ],
        },
    },
]

ASGI_APPLICATION = 'ARPBIGIDISBA_frontend.asgi.application'

WSGI_APPLICATION = 'ARPBIGIDISBA_frontend.wsgi.application'

# django_plotly_dash configuration to use frames within HTML documents
X_FRAME_OPTIONS = 'SAMEORIGIN'

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': os.environ.get('DB_NAME'),
    #     'USER': os.environ.get('DB_USER'),
    #     'PASSWORD': os.environ.get('DB_PASSWORD'),
    #     'HOST': os.environ.get('DB_HOST'),
    #     'PORT': '3306',
    #     "connect_timeout": 180,
    # }

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'psdb_pre',
        'USER': 'remote_user',
        'PASSWORD': '@rpB1Gserver',
        'HOST': '165.22.89.54',  # 'db', arpbig_ps, os.environ.get('DB_HOST'), 127.0.0.1,
        "connect_timeout": 180,
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/accounts/login/'  # URL to redirect to if the user is not authenticated
LOGIN_REDIRECT_URL = '/'  # Page to redirect to after logging in
LOGOUT_REDIRECT_URL = '/'  # Page to redirect to after logging out

# Names of public views for authentication middleware
LOGIN_NOT_REQUIRED_URLNAMES = [
    'login',
    'logout',
]

# Exact paths for public views for authentication middleware
LOGIN_NOT_REQUIRED_PATHS = [
    '/accounts/login/',
    '/accounts/logout/',
]

# Rutas que requieren rol Editor o Administrador (escritura en BD)
EDITOR_REQUIRED_PATHS = [
    '/cargadatos',
    '/upload_summary',
    '/upload_confirm',
    '/upload_modal',
    '/fk_save',
    '/descargar_manual_bdd',
    '/strain_bank/edit/',
    '/strain_bank/delete/',
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# Default language
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# Activate traduction support
USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = [
    BASE_DIR / "static",

]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

## PlotlyDash Configuration
STATICFILES_FINDERS = [

    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',

    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
    'django_plotly_dash.finders.DashAppDirectoryFinder',
]

## Jazzmin Configuration
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "ARPBIG DB",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "ARPBIG database",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": None,

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "img/Logo_arpbig_fondo_transparente_colores_blanco_letras_blanco.png",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-fluid",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "img/arpbig-high-resolution-logo-black-transparent(2).ico",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "img/Logo_arpbig_fondo_transparente_negro.png",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the ARPBIG database administrator",

    # Copyright on the footer
    "copyright": "Propiedad de ARPBIG - ARPBIG property",

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [


        # Url that gets reversed (Permissions can be added)
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        {"name": "PRO environment ARPBIG", "url": "https://db.arpbigidisba.com", "new_window": True},

        # external url that opens in a new window (Permissions can be added)
        {"name": "PRE environment ARPBIG", "url": "https://predb.arpbigidisba.com", "new_window": True},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"name": "Modelos", "app": "home"},
    ],

    #############
    # User Menu #
    #############

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": ['dashboard'],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["home", "auth"],

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,
    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": True,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

## Logging Configuration
LOGS_DIR = BASE_DIR.parent / 'logs'
LOGS_DIR.mkdir(exist_ok=True)  # Crea el directorio si no existe

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'access_denied': {
            'format': '%(asctime)s %(levelname)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'access_denied_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(LOGS_DIR / 'access_denied.log'),
            'when': 'midnight',       # Rotates every day at midnight
            'backupCount': 30,        # Keeps 30 days of log history
            'formatter': 'access_denied',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'home.middleware': {
            'handlers': ['access_denied_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}