# Generated by Django 4.2.19 on 2025-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('clone', models.CharField(blank=True, max_length=200, null=True)),
                ('plasmid', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('frozen_date', models.DateField()),
                ('responsible', models.CharField(max_length=200)),
                ('publication_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('strain', models.CharField(max_length=200)),
                ('rack', models.CharField(max_length=10)),
                ('rack_row', models.CharField(max_length=2)),
                ('rack_col', models.CharField(max_length=2)),
                ('box', models.CharField(max_length=10)),
                ('box_row', models.CharField(max_length=2)),
                ('box_col', models.CharField(max_length=2)),
            ],
        ),
    ]
