# Generated by Django 4.2.19 on 2025-09-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='box',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='box_col',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='box_row',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='frozen_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='rack',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='rack_col',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='rack_row',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='species',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='strain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
