# Generated by Django 4.2.19 on 2025-09-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_sample_box_alter_sample_box_col_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='freezer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
