# Generated by Django 4.2.19 on 2025-09-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_sample_freezer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='freezer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
