# Generated by Django 4.2.13 on 2024-06-21 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcquiredResistome',
            fields=[
                ('acquired_resistome_id', models.AutoField(primary_key=True, serialize=False)),
                ('acquired_gene_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gene_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'acquired_resistome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assembler',
            fields=[
                ('assembler_id', models.AutoField(primary_key=True, serialize=False)),
                ('assembler_name', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'assembler',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlowcellKit',
            fields=[
                ('flowcell_kit_id', models.AutoField(primary_key=True, serialize=False)),
                ('flowcell_kit_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'flowcell_kit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_code', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HypermutationGene',
            fields=[
                ('hypermutation_gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('official_name', models.CharField(blank=True, max_length=6, null=True)),
                ('synonym_name', models.CharField(blank=True, max_length=6, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'hypermutation_gene',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvitroSerotype',
            fields=[
                ('invitro_serotype_id', models.AutoField(primary_key=True, serialize=False)),
                ('invitro_value', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'invitro_serotype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LocusMlst',
            fields=[
                ('mlst_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('official_name', models.CharField(blank=True, max_length=6, null=True)),
                ('synonym_name', models.CharField(blank=True, max_length=6, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'locus_mlst',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetadataGeneral',
            fields=[
                ('isolate_id', models.AutoField(primary_key=True, serialize=False)),
                ('isolate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('isolate_project_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('isolation_day', models.IntegerField(blank=True, null=True)),
                ('isolation_month', models.IntegerField(blank=True, null=True)),
                ('isolation_year', models.IntegerField(blank=True, null=True)),
                ('isolation_date', models.DateField(blank=True, null=True)),
                ('isolate_source', models.CharField(blank=True, max_length=255, null=True)),
                ('isolate_comments', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'metadata_general',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mic',
            fields=[
                ('mic_id', models.AutoField(primary_key=True, serialize=False)),
                ('pip', models.CharField(blank=True, max_length=10, null=True)),
                ('pip_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('pip_tz', models.CharField(blank=True, max_length=10, null=True)),
                ('pip_tz_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('fep', models.CharField(blank=True, max_length=10, null=True)),
                ('fep_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('cfdc', models.CharField(blank=True, max_length=10, null=True)),
                ('cfdc_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('caz', models.CharField(blank=True, max_length=10, null=True)),
                ('caz_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('caz_avi', models.CharField(blank=True, max_length=10, null=True)),
                ('caz_avi_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('ct', models.CharField(blank=True, max_length=10, null=True)),
                ('ct_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('imi', models.CharField(blank=True, max_length=10, null=True)),
                ('imi_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('imi_rel', models.CharField(blank=True, max_length=10, null=True)),
                ('imi_rel_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('mer', models.CharField(blank=True, max_length=10, null=True)),
                ('mer_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('mer_vab', models.CharField(blank=True, max_length=10, null=True)),
                ('mer_vab_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('azt', models.CharField(blank=True, max_length=10, null=True)),
                ('azt_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('azt_avi', models.CharField(blank=True, max_length=10, null=True)),
                ('azt_avi_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('cip', models.CharField(blank=True, max_length=10, null=True)),
                ('cip_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('dlx', models.CharField(blank=True, max_length=10, null=True)),
                ('dlx_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('lvx', models.CharField(blank=True, max_length=10, null=True)),
                ('lvx_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('mxl', models.CharField(blank=True, max_length=10, null=True)),
                ('mxl_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('ami', models.CharField(blank=True, max_length=10, null=True)),
                ('ami_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('gen', models.CharField(blank=True, max_length=10, null=True)),
                ('gen_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('net', models.CharField(blank=True, max_length=10, null=True)),
                ('net_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('tob', models.CharField(blank=True, max_length=10, null=True)),
                ('tob_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('col', models.CharField(blank=True, max_length=10, null=True)),
                ('col_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('fo', models.CharField(blank=True, max_length=10, null=True)),
                ('fo_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('tic', models.CharField(blank=True, max_length=10, null=True)),
                ('tic_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('ptz', models.CharField(blank=True, max_length=10, null=True)),
                ('ptz_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('taz', models.CharField(blank=True, max_length=10, null=True)),
                ('taz_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('cza', models.CharField(blank=True, max_length=10, null=True)),
                ('cza_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('tol', models.CharField(blank=True, max_length=10, null=True)),
                ('tol_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('atm', models.CharField(blank=True, max_length=10, null=True)),
                ('atm_clinical_category', models.CharField(blank=True, max_length=2, null=True)),
                ('caz_cloxa', models.CharField(blank=True, max_length=3, null=True)),
                ('imi_cloxa', models.CharField(blank=True, max_length=3, null=True)),
                ('mic_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('isolate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral')),
            ],
            options={
                'db_table': 'mic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MutationalResistome',
            fields=[
                ('mutational_resistome_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('official_name', models.CharField(blank=True, max_length=6, null=True)),
                ('synonym_name', models.CharField(blank=True, max_length=6, null=True)),
                ('pbp_name', models.CharField(blank=True, max_length=6, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mutational_resistome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('sample_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sample_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SequencingLibrary',
            fields=[
                ('sequencing_library_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequencing_library_method', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sequencing_library',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SequencingPlatform',
            fields=[
                ('sequencing_platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequencing_platform_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sequencing_platform_supplier', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sequencing_platform',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SequencingTechnology',
            fields=[
                ('sequencing_technology_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequencing_technology_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reads_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sequencing_technology',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VirulenceGene',
            fields=[
                ('virulence_gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('official_name', models.CharField(blank=True, max_length=6, null=True)),
                ('synonym_name', models.CharField(blank=True, max_length=6, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'virulence_gene',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SequencingInfo',
            fields=[
                ('sequencing_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequencing_goal', models.CharField(blank=True, max_length=100, null=True)),
                ('sequencing_source', models.CharField(blank=True, max_length=100, null=True)),
                ('flowcell_kit', models.ForeignKey(blank=True, db_column='flowcell_kit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.flowcellkit')),
                ('isolate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral')),
                ('library_method', models.ForeignKey(blank=True, db_column='library_method', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sequencinglibrary')),
                ('sequencing_platform', models.ForeignKey(blank=True, db_column='sequencing_platform', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sequencingplatform')),
                ('sequencing_technology', models.ForeignKey(blank=True, db_column='sequencing_technology', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sequencingtechnology')),
            ],
            options={
                'db_table': 'sequencing_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SequenceAnalysis',
            fields=[
                ('sequence_analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('mlst_allelic_profile', models.JSONField(blank=True, null=True)),
                ('sequence_type', models.CharField(blank=True, max_length=10, null=True)),
                ('clonal_complex', models.CharField(blank=True, max_length=10, null=True)),
                ('mutational_resistome', models.JSONField(blank=True, null=True)),
                ('acquired_resistome', models.JSONField(blank=True, null=True)),
                ('virulence_genes', models.JSONField(blank=True, null=True)),
                ('hypermutation_genes', models.JSONField(blank=True, null=True)),
                ('insilico_serotype', models.CharField(blank=True, max_length=3, null=True)),
                ('betalactamase_pcr', models.JSONField(blank=True, null=True)),
                ('isolate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral')),
            ],
            options={
                'db_table': 'sequence_analysis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhenotypicData',
            fields=[
                ('phenotypic_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('ab_susceptibility_method', models.CharField(blank=True, max_length=100, null=True)),
                ('ecdc_resistance_profile', models.CharField(blank=True, max_length=3, null=True)),
                ('idsa_resistance_profile', models.CharField(blank=True, max_length=3, null=True)),
                ('cloxa_test', models.CharField(blank=True, max_length=3, null=True)),
                ('mbl_test', models.CharField(blank=True, max_length=3, null=True)),
                ('esbl_test', models.CharField(blank=True, max_length=3, null=True)),
                ('class_a_carbapenemase_test', models.CharField(blank=True, max_length=3, null=True)),
                ('hypermutator_phenotype', models.CharField(blank=True, max_length=15, null=True)),
                ('invitro_serotype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.invitroserotype')),
                ('isolate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral')),
                ('mic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.mic')),
            ],
            options={
                'db_table': 'phenotypic_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetadataClinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('isolate_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('patient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_ward', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital', models.ForeignKey(blank=True, db_column='hospital', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.hospital')),
            ],
            options={
                'db_table': 'metadata_clinic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('file_path_id', models.AutoField(primary_key=True, serialize=False)),
                ('fastq_path', models.CharField(blank=True, max_length=255, null=True)),
                ('denovo_assembly_path', models.CharField(blank=True, max_length=255, null=True)),
                ('assembler', models.ForeignKey(blank=True, db_column='assembler', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.assembler')),
                ('isolate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral')),
            ],
            options={
                'db_table': 'file_path',
                'managed': True,
            },
        ),
    ]
