# Generated by Django 4.2.19 on 2025-05-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcquiredResistome',
            fields=[
                ('acquired_resistome_id', models.AutoField(primary_key=True, serialize=False)),
                ('acquired_gene_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gene_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'acquired_resistome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assembler',
            fields=[
                ('assembler_id', models.AutoField(primary_key=True, serialize=False)),
                ('assembler_name', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'assembler',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BreakpointTable',
            fields=[
                ('breakpoint_table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_version_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tabla Puntos de corte')),
                ('table_version_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Versíón de tabla')),
                ('valid_date', models.DateTimeField(verbose_name='Fecha inicio de validez')),
                ('organism', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organismo')),
                ('organization', models.CharField(blank=True, max_length=50, null=True, verbose_name='Organización')),
                ('filepath', models.FilePathField(blank=True, max_length=255, null=True)),
                ('mic_breakpoints', models.JSONField(blank=True, null=True)),
                ('zd_breakpoints', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'breakpoint',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FlowcellKit',
            fields=[
                ('flowcell_kit_id', models.AutoField(primary_key=True, serialize=False)),
                ('flowcell_kit_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'flowcell_kit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(db_column='hospital_id', primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre hospital')),
                ('hospital_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código hospital')),
                ('hospital_ccn', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código CCN hospital')),
                ('hospital_codcnh', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código CODCNH hospital')),
                ('hospital_comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios hospital')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='País')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comunidad autónoma')),
                ('sub_region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Provincia')),
                ('town', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidad')),
                ('geo_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('geo_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
            ],
            options={
                'db_table': 'hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HypermutationGene',
            fields=[
                ('hypermutation_gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('official_name', models.CharField(blank=True, max_length=6, null=True)),
                ('synonym_name', models.CharField(blank=True, max_length=6, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'hypermutation_gene',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvitroSerotype',
            fields=[
                ('invitro_serotype_id', models.AutoField(primary_key=True, serialize=False)),
                ('invitro_value', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'invitro_serotype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LocusMlst',
            fields=[
                ('mlst_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('official_name', models.CharField(blank=True, max_length=6, null=True)),
                ('synonym_name', models.CharField(blank=True, max_length=6, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'locus_mlst',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetadataGeneral',
            fields=[
                ('isolate_id', models.AutoField(primary_key=True, serialize=False)),
                ('isolate_name', models.CharField(blank=True, db_comment='Isolate name in its project', max_length=50, null=True, verbose_name='Isolate name')),
                ('isolate_project_code', models.CharField(blank=True, db_comment='Official project code', max_length=50, null=True, unique=True, verbose_name='Project code')),
                ('species', models.CharField(blank=True, db_comment='Isolate species', max_length=255, null=True, verbose_name='Species')),
                ('project_name', models.CharField(blank=True, db_comment='Internal name of the project', max_length=255, null=True, verbose_name='Project name')),
                ('isolation_day', models.IntegerField(blank=True, db_comment='Isolate obtention day', null=True, verbose_name='Isolate obtention day')),
                ('isolation_month', models.IntegerField(blank=True, db_comment='Isolate obtention month', null=True, verbose_name='Isolate obtention month')),
                ('isolation_year', models.IntegerField(blank=True, db_comment='Isolate obtention year', null=True, verbose_name='Isolate obtention year')),
                ('isolation_date', models.DateField(blank=True, db_comment='Whole date of obtention of the isolate', null=True, verbose_name='Isolate obtention date')),
                ('isolate_source', models.CharField(blank=True, db_comment='Clinic origin of the isolate', max_length=255, null=True, verbose_name='Isolate origin')),
                ('isolate_comments', models.CharField(blank=True, db_comment='Comments about the isolate', max_length=255, null=True, verbose_name='Isolate comments')),
            ],
            options={
                'db_table': 'metadata_general',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mic',
            fields=[
                ('mic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='MIC_id')),
                ('pip', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de piperacilina', help_text='PIP-ARO:0000078', max_length=10, null=True, verbose_name='Piperacillin')),
                ('pip_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a piperacilina', help_text='PIP-ARO:0000078 clinical category', max_length=2, null=True, verbose_name='Piperacillin clinical category')),
                ('pip_tz', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de piperacilina/tazobactam', help_text='PIP/TZ-ARO:3004021', max_length=10, null=True, verbose_name='Piperacillin/Tazobactam')),
                ('pip_tz_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a piperacilina/tazobactam', help_text='PIP/TZ-ARO:3004021 clinical category', max_length=2, null=True, verbose_name='Piperacillin/Tazobactam clinical category')),
                ('fep', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de cefepima', help_text='FEP-ARO:0000059', max_length=10, null=True, verbose_name='Cefepime')),
                ('fep_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefepima', help_text='FEP-ARO:0000059 clinical category', max_length=2, null=True, verbose_name='Cefepime clinical category')),
                ('cfdc', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de cefiderocol', help_text='FDC-ARO:3004474', max_length=10, null=True, verbose_name='Cefiderocol')),
                ('cfdc_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefiderocol', help_text='FDC-ARO:3004474 clinical category', max_length=2, null=True, verbose_name='Cefiderocol clinical category')),
                ('caz', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftazidima', help_text='CAZ-ARO:0000060', max_length=10, null=True, verbose_name='Ceftazidime')),
                ('caz_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftazidima', help_text='CAZ-ARO:0000060 clinical category', max_length=2, null=True, verbose_name='Ceftazidime clinical category')),
                ('caz_avi', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftazidima/avibactam', help_text='CAZ/AVI-ARO:3007072', max_length=10, null=True, verbose_name='Ceftazidime/Avibactam')),
                ('caz_avi_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftazidima/avibactam', help_text='CAZ/AVI-ARO:3007072 clinical category', max_length=2, null=True, verbose_name='Ceftazidime/Avibactam clinical category')),
                ('tol', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftolozano', help_text='TOL-ARO:3003927', max_length=10, null=True, verbose_name='Ceftolozane')),
                ('tol_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tebipenem pivoxil', help_text='TOL-ARO:3003927 clinical category', max_length=2, null=True, verbose_name='Ceftolozane clinical category')),
                ('ctz', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftolozano/tazobactam', help_text='TOL/TZ-ARO:3004724', max_length=10, null=True, verbose_name='Ceftolozane/Tazobactam')),
                ('ctz_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftolozano', help_text='TOL/TZ-ARO:3004724 clinical category', max_length=2, null=True, verbose_name='Ceftolozane/Tazobactam clinical category')),
                ('imi', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de imipenem', help_text='IMI-ARO:3000170', max_length=10, null=True, verbose_name='Imipenem')),
                ('imi_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a imipenem', help_text='IMI-ARO:3000170 clinical category', max_length=2, null=True, verbose_name='Imipenem clinical category')),
                ('imi_rel', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de imipenem/relebactam', help_text='IMI/REL-ARO:????????', max_length=10, null=True, verbose_name='Imipenem/Relebactam')),
                ('imi_rel_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a imipenem/relebactam', help_text='IMI/REL-ARO:???????? clinical category', max_length=2, null=True, verbose_name='Imipenem/Relebactam clinical category')),
                ('mer', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de meropenem', help_text='MER-ARO:0000073', max_length=10, null=True, verbose_name='Meropenem')),
                ('mer_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem', help_text='MER-ARO:0000073 clinical category', max_length=2, null=True, verbose_name='Meropenem clinical category')),
                ('mer_vab', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de meropenem/vaborbactam', help_text='MER/VAB-ARO:3007146', max_length=10, null=True, verbose_name='Meropenem/Vaborbactam')),
                ('mer_vab_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem/vaborbactam', help_text='MER/VAB-ARO:3007146 clinical category', max_length=2, null=True, verbose_name='Meropenem/Vaborbactam clinical category')),
                ('atm', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de aztreonam', help_text='AZT-ARO:3000550', max_length=10, null=True, verbose_name='Aztreonam')),
                ('atm_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a aztreonam', help_text='AZT-ARO:3000550 clinical category', max_length=2, null=True, verbose_name='Aztreonam clinical category')),
                ('azt_avi', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de aztreonam/avibactam', help_text='AZT/AVI-ARO:3007366', max_length=10, null=True, verbose_name='Aztreonam/Avibactam')),
                ('azt_avi_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a aztreonam/avibactam', help_text='AZT/AVI-ARO:3007366 clinical category', max_length=2, null=True, verbose_name='Aztreonam/Avibactam clinical category')),
                ('cip', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ciprofloxacino', help_text='CIP-ARO:0000036', max_length=10, null=True, verbose_name='Ciprofloxacin')),
                ('cip_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ciprofloxacino', help_text='CIP-ARO:0000036 clinical category', max_length=2, null=True, verbose_name='Ciprofloxacin clinical category')),
                ('dlx', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de delafloxacino', help_text='DLX-ARO:3004462', max_length=10, null=True, verbose_name='Delafloxacin')),
                ('dlx_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a delafloxacino', help_text='DLX-ARO:3004462 clinical category', max_length=2, null=True, verbose_name='Delafloxacin clinical category')),
                ('lvx', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de levofloxacino', help_text='LVX-ARO:0000071', max_length=10, null=True, verbose_name='Levofloxacin')),
                ('lvx_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a levofloxacino', help_text='LVX-ARO:0000071 clinical category', max_length=2, null=True, verbose_name='Levofloxacin clinical category')),
                ('mxl', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de moxifloxacino', help_text='MXL-ARO:0000074', max_length=10, null=True, verbose_name='Moxifloxacin')),
                ('mxl_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a moxifloxacino', help_text='MXL-ARO:0000074 clinical category', max_length=2, null=True, verbose_name='Moxifloxacin clinical category')),
                ('ami', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de amikacina', help_text='AMI-ARO:0000013', max_length=10, null=True, verbose_name='Amikacin')),
                ('ami_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a amikacina', help_text='AMI-ARO:0000013 clinical category', max_length=2, null=True, verbose_name='Amikacin clinical category')),
                ('gen', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de gentamicina', help_text='GEN-ARO:3007382', max_length=10, null=True, verbose_name='Gentamycin')),
                ('gen_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a gentamicina', help_text='GEN-ARO:3007382 clinical category', max_length=2, null=True, verbose_name='Gentamycin clinical category')),
                ('net', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de netilmicina', help_text='NET-ARO:0000038', max_length=10, null=True, verbose_name='Netilmycin')),
                ('net_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a netilmicina', help_text='NET-ARO:0000038 clinical category', max_length=2, null=True, verbose_name='Netilmycin clinical category')),
                ('tob', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de tobramicina', help_text='TOB-ARO:0000052', max_length=10, null=True, verbose_name='Tobramycin')),
                ('tob_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tobramicina', help_text='TOB-ARO:0000052 clinical category', max_length=2, null=True, verbose_name='Tobramycin clinical category')),
                ('col', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de colistina', help_text='COL-ARO:0000067', max_length=10, null=True, verbose_name='Colistin')),
                ('col_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a colistina', help_text='COL-ARO:0000067 clinical category', max_length=2, null=True, verbose_name='Colistin clinical category')),
                ('fo', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de fosfomicina', help_text='FOS-ARO:0000025', max_length=10, null=True, verbose_name='Fosfomycin')),
                ('fo_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a fosfomicina', help_text='FOS-ARO:0000025 clinical category', max_length=2, null=True, verbose_name='Fosfomycin clinical category')),
                ('tic', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ticarcilina', help_text='TIC-ARO:3003832', max_length=10, null=True, verbose_name='Ticarcillin')),
                ('tic_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ticarcilina', help_text='TIC-ARO:3003832 clinical category', max_length=2, null=True, verbose_name='Ticarcillin clinical category')),
                ('ptz', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de piperacilina/tazobactam', help_text='PIP/TZ-ARO:3004021', max_length=10, null=True, verbose_name='Piperacillin/Tazobactam')),
                ('ptz_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a piperacilina/tazobactam', help_text='PIP/TZ-ARO:3004021 clinical category', max_length=2, null=True, verbose_name='Piperacillin/Tazobactam clinical category')),
                ('taz', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de tazobactam', help_text='TZ-ARO:0000077', max_length=10, null=True, verbose_name='Tazobactam')),
                ('taz_clinical_category', models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tazobactam', help_text='TZ-ARO:0000077 clinical category', max_length=2, null=True, verbose_name='Tazobactam clinical category')),
                ('caz_cloxa', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftazidima/cloxacilina', max_length=3, null=True)),
                ('imi_cloxa', models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de imipenem/cloxacilina', max_length=3, null=True)),
                ('mic_comments', models.CharField(blank=True, db_comment='Comentarios de la concentración mínima inhibitoria', max_length=255, null=True)),
                ('isolate_id', models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral')),
            ],
            options={
                'verbose_name': 'MIC',
                'db_table': 'mic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MutationalResistome',
            fields=[
                ('mutational_resistome_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('official_name', models.CharField(blank=True, max_length=6, null=True)),
                ('synonym_name', models.CharField(blank=True, max_length=6, null=True)),
                ('pbp_name', models.CharField(blank=True, max_length=6, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mutational_resistome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('sample_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Tipo de muestra')),
                ('sample', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de muestra')),
            ],
            options={
                'db_table': 'sample_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SequencingLibrary',
            fields=[
                ('sequencing_library_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequencing_library_method', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sequence libraries',
                'db_table': 'sequencing_library',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SequencingPlatform',
            fields=[
                ('sequencing_platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequencing_platform_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sequencing_platform_supplier', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sequencing_platform',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SequencingTechnology',
            fields=[
                ('sequencing_technology_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequencing_technology_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reads_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sequencing technologies',
                'db_table': 'sequencing_technology',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VirulenceGene',
            fields=[
                ('virulence_gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('official_name', models.CharField(blank=True, max_length=6, null=True)),
                ('synonym_name', models.CharField(blank=True, max_length=6, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'virulence_gene',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SequencingInfo',
            fields=[
                ('sequencing_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequencing_goal', models.CharField(blank=True, db_comment='Objective for sequencing this isolate', max_length=100, null=True, verbose_name='Sequencing goal')),
                ('sequencing_source', models.CharField(blank=True, db_comment='Where was the sequencing obtained', max_length=100, null=True, verbose_name='Sequencing source')),
                ('flowcell_kit', models.ForeignKey(blank=True, db_column='flowcell_kit_id', db_comment='Flowcell Kit utilizado en la secuenciación', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.flowcellkit')),
                ('isolate_id', models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral')),
                ('library_method', models.ForeignKey(blank=True, db_column='library_method_id', db_comment='Método de preparación de la librería', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sequencinglibrary')),
                ('sequencing_platform', models.ForeignKey(blank=True, db_column='sequencing_platform_id', db_comment='Plataforma de secuenciación para obtener el aislado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sequencingplatform')),
                ('sequencing_technology', models.ForeignKey(blank=True, db_column='sequencing_technology_id', db_comment='Tecnología de secuenciación para obtener el aislado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sequencingtechnology')),
            ],
            options={
                'db_table': 'sequencing_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SequenceAnalysis',
            fields=[
                ('sequence_analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('mlst_allelic_profile', models.JSONField(blank=True, db_comment='Allelic values of loci used in multilocus strain typing, using JSON format', null=True, verbose_name='MLST allelic profile')),
                ('sequence_type', models.CharField(blank=True, db_comment='Sequence type of the isolate', max_length=10, null=True, verbose_name='Sequence type')),
                ('clonal_complex', models.CharField(blank=True, db_comment='Clonal complex of the isolate', max_length=10, null=True, verbose_name='Clonal complex')),
                ('mutational_resistome', models.JSONField(blank=True, db_comment='Mutational resistome, using JSON format', null=True)),
                ('ame_loci', models.CharField(blank=True, db_comment='Aminoglycoside modifying enzymes loci, name list comma-separated', max_length=500, null=True, verbose_name='AME loci')),
                ('beta_lactamase_loci', models.CharField(blank=True, db_comment='Beta-lactamases/Carbapenemases loci, name list comma-separated', max_length=500, null=True, verbose_name='Beta-lactamases/Carbapenemases loci')),
                ('fluoroquinolones_loci', models.CharField(blank=True, db_comment='Fluoroquinolones resistance determinants loci, name list comma-separated', max_length=500, null=True, verbose_name='Fluoroquinolones resistance determinants')),
                ('other_acq_loci', models.CharField(blank=True, db_comment='Other acquired resistance determinants, name list comma-separated', max_length=500, null=True, verbose_name='Other acquired resistance determinants')),
                ('acquired_resistome', models.JSONField(blank=True, db_comment='Acquired resistome, in JSON format', null=True)),
                ('virulence_genes', models.JSONField(blank=True, db_comment='Virulencia genes, in JSON format', null=True)),
                ('hypermutation_genes', models.JSONField(blank=True, db_comment='Hypermutation genes, in JSON format', null=True)),
                ('insilico_serotype', models.CharField(blank=True, db_comment='Phenotypic in silico serotype of the isolate', max_length=3, null=True, verbose_name='In silico serotype')),
                ('betalactamase_pcr', models.JSONField(blank=True, db_comment='Beta-lactamases PCR results, in JSON format', null=True)),
                ('isolate_id', models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral')),
            ],
            options={
                'verbose_name_plural': 'Sequence Analyses',
                'db_table': 'sequence_analysis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhenotypicData',
            fields=[
                ('phenotypic_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('atb_susceptibility_method', models.CharField(blank=True, choices=[('DD', 'Disc diffusion (halo diameter in mm.)'), ('BM', 'Broth microdilution (mg/L)'), ('ET', 'E-test'), ('OT', 'Other')], db_comment='Method used to determine antibiotic susceptibility', max_length=100, null=True, verbose_name='ATB susceptibility method')),
                ('atb_susceptibility_method_other', models.CharField(blank=True, db_comment='Other method used to determine antibiotic susceptibility', max_length=100, null=True, verbose_name='ATB susceptibility other method')),
                ('broth_type', models.CharField(blank=True, choices=[('IH', 'In-house)'), ('CM', 'Commercial')], db_comment='Type of broth used in the susceptibility test', max_length=100, null=True, verbose_name='Broth type')),
                ('commercial_panel_name', models.CharField(blank=True, db_comment='Name of the commercial panel used in the susceptibility test', max_length=100, null=True, verbose_name='Commercial panel name')),
                ('ecdc_resistance_profile', models.CharField(blank=True, db_comment='Resistance profile following ECDC guidelines', max_length=3, null=True, verbose_name='ECDC profile')),
                ('idsa_resistance_profile', models.CharField(blank=True, db_comment='Resistance profile following IDSA guidelines', max_length=3, null=True, verbose_name='IDSA profile')),
                ('cloxa_test', models.CharField(blank=True, db_comment='CLOXA test result, accepted values: +/-', max_length=3, null=True, verbose_name='CLOXA test')),
                ('mbl_test', models.CharField(blank=True, db_comment='MBL test result, accepted values: +/-', max_length=3, null=True, verbose_name='MBL test')),
                ('esbl_test', models.CharField(blank=True, db_comment='ESBL test result, accepted values: +/-', max_length=3, null=True, verbose_name='ESBL test')),
                ('class_a_carbapenemase_test', models.CharField(blank=True, db_comment='Class A carbapenemases test result', max_length=3, null=True, verbose_name='Class A carbapenemases')),
                ('hypermutator_phenotype', models.CharField(blank=True, db_comment='Hypermutator phenotype', max_length=15, null=True, verbose_name='Hypermutator phenotype')),
                ('phenotypic_comments', models.TextField(blank=True, db_comment='Comments about isolate phenotype characteristics', null=True, verbose_name='Phenotypic comments')),
                ('invitro_serotype', models.ForeignKey(blank=True, db_column='invitro_serotype_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.invitroserotype', verbose_name='In vitro serotype')),
                ('isolate_id', models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral')),
                ('mic', models.ForeignKey(blank=True, db_column='mic_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.mic')),
            ],
            options={
                'verbose_name_plural': 'Phenotypic Data',
                'db_table': 'phenotypic_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetadataClinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_code', models.CharField(blank=True, db_comment='Code of the patient in the project', max_length=255, null=True, verbose_name='Patient code')),
                ('collection_ward', models.CharField(blank=True, db_comment='Name of the departament where the isolate was obtained', max_length=255, null=True, verbose_name='Ward')),
                ('hospital', models.ForeignKey(blank=True, db_column='hospital_id', db_comment='Name of the hospital where the isolate was obtained', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospitals', to='home.hospital', verbose_name='Hospital')),
                ('isolate_id', models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral')),
                ('sample_type', models.ForeignKey(blank=True, db_column='sample_type_id', db_comment='Type of the sample from which the isolate was obtained', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sampletype', verbose_name='Sample type')),
            ],
            options={
                'db_table': 'metadata_clinic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('file_path_id', models.AutoField(primary_key=True, serialize=False)),
                ('fastq_path', models.CharField(blank=True, db_comment='Path to the folder where FASTQ files of the isolate are stored', max_length=255, null=True, verbose_name='FASTQ path')),
                ('denovo_assembly_path', models.CharField(blank=True, db_comment='Path to the folder where de novo files of the isolate are stored', max_length=255, null=True, verbose_name='DeNovo files path')),
                ('assembler', models.ForeignKey(blank=True, db_column='assembler_id', db_comment='Ensamblador utilizado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.assembler')),
                ('isolate_id', models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral')),
            ],
            options={
                'db_table': 'file_path',
                'managed': True,
            },
        ),
    ]
