# Generated by Django 4.2.11 on 2024-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('archivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fastq', models.CharField(blank=True, max_length=255, null=True)),
                ('ensamblado', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'archivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fenotipo',
            fields=[
                ('fenotipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_suscept', models.CharField(blank=True, max_length=100, null=True)),
                ('cmi_id', models.CharField(blank=True, max_length=10, null=True)),
                ('cat_clinica', models.CharField(blank=True, max_length=3, null=True)),
                ('perfil_ecdc', models.CharField(blank=True, max_length=3, null=True)),
                ('perfil_idsa', models.CharField(blank=True, max_length=3, null=True)),
                ('test_cloxa', models.CharField(blank=True, max_length=3, null=True)),
                ('test_mbl', models.CharField(blank=True, max_length=3, null=True)),
                ('test_blee', models.CharField(blank=True, max_length=3, null=True)),
                ('test_carba_a', models.CharField(blank=True, db_column='test_carba_A', max_length=3, null=True)),
                ('serotipo_invitro', models.CharField(blank=True, max_length=3, null=True)),
                ('cevs', models.IntegerField(blank=True, null=True)),
                ('virulencia_galleria', models.IntegerField(blank=True, null=True)),
                ('fenot_hipermutador', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'fenotipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('libreria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'libreria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocusHipermutacion',
            fields=[
                ('hipermut_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_oficial', models.CharField(blank=True, max_length=6, null=True)),
                ('nombre_sinonimo', models.CharField(blank=True, max_length=6, null=True)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'locus_hipermutacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocusMlst',
            fields=[
                ('mlst_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_oficial', models.CharField(blank=True, max_length=6, null=True)),
                ('nombre_sinonimo', models.CharField(blank=True, max_length=6, null=True)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'locus_mlst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocusVirulencia',
            fields=[
                ('virulencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_oficial', models.CharField(blank=True, max_length=6, null=True)),
                ('nombre_sinonimo', models.CharField(blank=True, max_length=6, null=True)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'locus_virulencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetadataClinico',
            fields=[
                ('clinico_id', models.AutoField(primary_key=True, serialize=False)),
                ('paciente_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_muestra', models.CharField(blank=True, max_length=255, null=True)),
                ('servicio_obtencion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'metadata_clinico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetadataGeneral',
            fields=[
                ('aislado_id', models.AutoField(primary_key=True, serialize=False)),
                ('aislado_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('aislado_exportar_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('especie', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('aislamiento_dia', models.IntegerField(blank=True, null=True)),
                ('aislamiento_mes', models.IntegerField(blank=True, null=True)),
                ('aislamiento_year', models.IntegerField(blank=True, null=True)),
                ('aislamiento_fecha', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('parental_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metadata_general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mic',
            fields=[
                ('mic_id', models.AutoField(primary_key=True, serialize=False)),
                ('mic_fecha', models.DateField(blank=True, null=True)),
                ('pip', models.CharField(blank=True, max_length=10, null=True)),
                ('pip_tz', models.CharField(blank=True, max_length=10, null=True)),
                ('fep', models.CharField(blank=True, max_length=10, null=True)),
                ('cfdc', models.CharField(blank=True, max_length=10, null=True)),
                ('caz', models.CharField(blank=True, max_length=10, null=True)),
                ('caz_avi', models.CharField(blank=True, max_length=10, null=True)),
                ('ct', models.CharField(blank=True, max_length=10, null=True)),
                ('imi', models.CharField(blank=True, max_length=10, null=True)),
                ('imi_rel', models.CharField(blank=True, max_length=10, null=True)),
                ('mer', models.CharField(blank=True, max_length=10, null=True)),
                ('mer_vab', models.CharField(blank=True, max_length=10, null=True)),
                ('azt', models.CharField(blank=True, max_length=10, null=True)),
                ('azt_avi', models.CharField(blank=True, max_length=10, null=True)),
                ('cip', models.CharField(blank=True, max_length=10, null=True)),
                ('dlx', models.CharField(blank=True, max_length=10, null=True)),
                ('lvx', models.CharField(blank=True, max_length=10, null=True)),
                ('mxl', models.CharField(blank=True, max_length=10, null=True)),
                ('ami', models.CharField(blank=True, max_length=10, null=True)),
                ('gen', models.CharField(blank=True, max_length=10, null=True)),
                ('net', models.CharField(blank=True, max_length=10, null=True)),
                ('tob', models.CharField(blank=True, max_length=10, null=True)),
                ('col', models.CharField(blank=True, max_length=10, null=True)),
                ('fo', models.CharField(blank=True, max_length=10, null=True)),
                ('tic', models.CharField(blank=True, max_length=10, null=True)),
                ('ptz', models.CharField(blank=True, max_length=10, null=True)),
                ('taz', models.CharField(blank=True, max_length=10, null=True)),
                ('cza', models.CharField(blank=True, max_length=10, null=True)),
                ('tol', models.CharField(blank=True, max_length=10, null=True)),
                ('atm', models.CharField(blank=True, max_length=10, null=True)),
                ('caz_cloxa', models.CharField(blank=True, max_length=3, null=True)),
                ('imi_cloxa', models.CharField(blank=True, max_length=3, null=True)),
                ('mic_observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('plataforma_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'plataforma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResistomaAdquirido',
            fields=[
                ('resistoma_adq_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_funcion', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'resistoma_adquirido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResistomaMutante',
            fields=[
                ('resistoma_mut_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_oficial', models.CharField(blank=True, max_length=6, null=True)),
                ('nombre_sinonimo', models.CharField(blank=True, max_length=6, null=True)),
                ('nombre_pbp', models.CharField(blank=True, max_length=6, null=True)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'resistoma_mutante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secuencia',
            fields=[
                ('secuencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('perfil_mlst', models.JSONField(blank=True, null=True)),
                ('clon', models.CharField(blank=True, max_length=10, null=True)),
                ('complejo_clonal', models.CharField(blank=True, max_length=10, null=True)),
                ('resistoma_mutante', models.JSONField(blank=True, null=True)),
                ('resistoma_adquirido', models.JSONField(blank=True, null=True)),
                ('genes_virulencia', models.JSONField(blank=True, null=True)),
                ('genes_hipermutacion', models.JSONField(blank=True, null=True)),
                ('serotipo_insilico', models.CharField(blank=True, max_length=3, null=True)),
                ('betalactamasas_adquiridas', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secuencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secuenciacion',
            fields=[
                ('secuenciacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_sec', models.CharField(blank=True, max_length=100, null=True)),
                ('origen_sec', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'secuenciacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('tecnica_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('lecturas', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tecnica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('tipo_muestra_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_muestra',
                'managed': False,
            },
        ),
    ]
