# Generated by Django 4.2.13 on 2024-05-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'managed': False, 'verbose_name_plural': 'Hospitales'},
        ),
        migrations.AlterModelOptions(
            name='locushipermutacion',
            options={'managed': False, 'verbose_name': 'Locus hipermutación', 'verbose_name_plural': 'Loci hipermutación'},
        ),
        migrations.AlterModelOptions(
            name='locusmlst',
            options={'managed': False, 'verbose_name': 'Locus MLST', 'verbose_name_plural': 'Loci MLST'},
        ),
        migrations.AlterModelOptions(
            name='locusvirulencia',
            options={'managed': False, 'verbose_name': 'Locus virulencia', 'verbose_name_plural': 'Loci virulencia'},
        ),
        migrations.AlterModelOptions(
            name='metadataclinico',
            options={'managed': False, 'verbose_name': 'Dato clínico', 'verbose_name_plural': 'Datos clínicos'},
        ),
        migrations.AlterModelOptions(
            name='metadatageneral',
            options={'managed': False, 'verbose_name': 'Metadato general', 'verbose_name_plural': 'Metadatos generales'},
        ),
        migrations.AlterModelOptions(
            name='resistomaadquirido',
            options={'managed': False, 'verbose_name': 'Mutación resistoma adquirido', 'verbose_name_plural': 'Mutaciones resistoma adquirido'},
        ),
        migrations.AlterModelOptions(
            name='resistomamutante',
            options={'managed': False, 'verbose_name': 'Mutación resistoma mutacional', 'verbose_name_plural': 'Mutaciones resistoma mutacional'},
        ),
        migrations.AlterModelOptions(
            name='secuenciacion',
            options={'managed': False, 'verbose_name_plural': 'Secuenciaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipomuestra',
            options={'managed': False, 'verbose_name': 'Tipo de muestra', 'verbose_name_plural': 'Tipos de muestra'},
        ),
    ]
