# Generated by Django 4.2.24 on 2025-10-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestGenes',
            fields=[
                ('interest_genes_id', models.AutoField(primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_strain', models.CharField(blank=True, choices=[('AR', 'Antibiotic resistance'), ('HYP', 'Hypermutation'), ('-', 'N/A'), ('OT', 'Other')], max_length=100, null=True)),
                ('start_position', models.IntegerField(blank=True, null=True)),
                ('end_position', models.IntegerField(blank=True, null=True)),
                ('official_name', models.CharField(blank=True, max_length=6, null=True)),
                ('synonym_name', models.CharField(blank=True, max_length=6, null=True)),
                ('pbp_name', models.CharField(blank=True, max_length=6, null=True)),
                ('function', models.CharField(blank=True, choices=[('AR', 'Antibiotic resistance'), ('HYP', 'Hypermutation'), ('-', 'N/A'), ('OT', 'Other')], max_length=255, null=True)),
                ('subset', models.CharField(blank=True, choices=[('BASIC', 'Basic resistome'), ('CR', 'Cefiderocol resistance'), ('-', 'N/A'), ('OT', 'Other')], max_length=100, null=True)),
                ('polymorphisms', models.JSONField(blank=True, db_comment='Known polymorphisms, in JSON format', null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Gene of interest',
                'verbose_name_plural': 'Genes of interest',
                'db_table': 'genes_of_interest',
                'managed': True,
            },
        ),
    ]
