# Generated by Django 4.2.13 on 2024-06-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phenotypicdata',
            options={'managed': True, 'verbose_name_plural': 'PhenoTypic Data'},
        ),
        migrations.AlterModelOptions(
            name='sequenceanalysis',
            options={'managed': True, 'verbose_name_plural': 'Sequence Analyses'},
        ),
        migrations.AlterModelOptions(
            name='sequencinglibrary',
            options={'managed': True, 'verbose_name_plural': 'Sequence libraries'},
        ),
        migrations.AlterModelOptions(
            name='sequencingtechnology',
            options={'managed': True, 'verbose_name_plural': 'Sequencing technologies'},
        ),
    ]
