# Generated by Django 4.2.25 on 2026-05-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name_es', models.CharField(blank=True, db_comment='Name of the ward in spanish where the isolate was obtained', max_length=255, null=True, verbose_name='Ward name spanish')),
                ('ward_name_en', models.CharField(blank=True, db_comment='Name of the ward in english where the isolate was obtained', max_length=255, null=True, verbose_name='Ward name english')),
            ],
            options={
                'db_table': 'ward',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='mic',
            name='ptz',
        ),
        migrations.RemoveField(
            model_name='mic',
            name='ptz_clinical_category',
        ),
        migrations.RemoveField(
            model_name='sampletype',
            name='sample',
        ),
        migrations.AddField(
            model_name='mic',
            name='atb_synonyms',
            field=models.JSONField(blank=True, db_comment='Diccionario de antibióticos y sus sinónimos abreviados', default=dict, null=True, verbose_name='Antibiotic synonyms'),
        ),
        migrations.AddField(
            model_name='mic',
            name='avi',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de avibactam', help_text='AVI-ARO:3000588', max_length=10, null=True, verbose_name='Avibactam'),
        ),
        migrations.AddField(
            model_name='mic',
            name='avi_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a avibactam', help_text='AVI-ARO:3000588 clinical category', max_length=2, null=True, verbose_name='Avibactam clinical category'),
        ),
        migrations.AddField(
            model_name='mic',
            name='dur',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de durlobactam', help_text='DUR-ARO:3007293', max_length=10, null=True, verbose_name='Durlobactam'),
        ),
        migrations.AddField(
            model_name='mic',
            name='dur_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a durlobactam', help_text='DUR-ARO:3007293 clinical category', max_length=2, null=True, verbose_name='Durlobactam clinical category'),
        ),
        migrations.AddField(
            model_name='mic',
            name='fdc_xer',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de cefiderocol/xeruborbactam', help_text='FDC_XER-ARO:????????', max_length=10, null=True, verbose_name='Cefiderocol/Xeruborbactam'),
        ),
        migrations.AddField(
            model_name='mic',
            name='fdc_xer_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefiderocol/xeruborbactam', help_text='FDC_XER-ARO:???????? clinical category', max_length=2, null=True, verbose_name='Cefiderocol/Xeruborbactam clinical category'),
        ),
        migrations.AddField(
            model_name='mic',
            name='fep_tan',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de cefepime/taniborbactam', help_text='FEP_TAN-ARO:3007148', max_length=10, null=True, verbose_name='Cefepime/Taniborbactam'),
        ),
        migrations.AddField(
            model_name='mic',
            name='fep_tan_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefepime/taniborbactam', help_text='FEP_TAN-ARO:3007148 clinical category', max_length=2, null=True, verbose_name='Cefepime/Taniborbactam clinical category'),
        ),
        migrations.AddField(
            model_name='mic',
            name='fep_zid',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de cefepime/zidebactam', help_text='FEP_ZID-ARO:???????', max_length=10, null=True, verbose_name='Cefepime/Zidebactam'),
        ),
        migrations.AddField(
            model_name='mic',
            name='fep_zid_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefepime/zidebactam', help_text='FEP_ZID-ARO:??????? clinical category', max_length=2, null=True, verbose_name='Cefepime/Zidebactam clinical category'),
        ),
        migrations.AddField(
            model_name='mic',
            name='mer_nac',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de meropenem/nacubactam', help_text='MER_NAC-ARO:????????', max_length=10, null=True, verbose_name='Meropenem/Nacubactam'),
        ),
        migrations.AddField(
            model_name='mic',
            name='mer_nac_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem/nacubactam', help_text='MER_NAC-ARO:???????? clinical category', max_length=2, null=True, verbose_name='Meropenem/Nacubactam clinical category'),
        ),
        migrations.AddField(
            model_name='mic',
            name='mer_xer',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de meropenem/xeruborbactam', help_text='MER_XER-ARO:????????', max_length=10, null=True, verbose_name='Meropenem/Xeruborbactam'),
        ),
        migrations.AddField(
            model_name='mic',
            name='mer_xer_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem/xeruborbactam', help_text='MER_XER-ARO:???????? clinical category', max_length=2, null=True, verbose_name='Meropenem/Xeruborbactam clinical category'),
        ),
        migrations.AddField(
            model_name='mic',
            name='nac',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de nacubactam', help_text='NAC-ARO:3007295', max_length=10, null=True, verbose_name='Nacubactam'),
        ),
        migrations.AddField(
            model_name='mic',
            name='nac_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a nacubactam', help_text='NAC-ARO:3007295 clinical category', max_length=2, null=True, verbose_name='Nacubactam clinical category'),
        ),
        migrations.AddField(
            model_name='mic',
            name='rel',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de relebactam', help_text='REL-ARO:3007031', max_length=10, null=True, verbose_name='Relebactam'),
        ),
        migrations.AddField(
            model_name='mic',
            name='rel_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a relebactam', help_text='REL-ARO:3007031 clinical category', max_length=2, null=True, verbose_name='Relebactam clinical category'),
        ),
        migrations.AddField(
            model_name='mic',
            name='xer',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de xeruborbactam', help_text='XER-ARO:3007048', max_length=10, null=True, verbose_name='Xeruborbactam'),
        ),
        migrations.AddField(
            model_name='mic',
            name='xer_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a xeruborbactam', help_text='XER-ARO:3007048 clinical category', max_length=2, null=True, verbose_name='Xeruborbactam clinical category'),
        ),
        migrations.AddField(
            model_name='sampletype',
            name='sample_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sample type in english'),
        ),
        migrations.AddField(
            model_name='sampletype',
            name='sample_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sample type in spanish'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='hospital',
            field=models.ForeignKey(blank=True, db_column='hospital_id', db_comment='Name of the hospital where the isolate was obtained', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospitals', to='home.hospital', verbose_name='Hospital'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='isolate_id',
            field=models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='home.metadatageneral'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='sample_type',
            field=models.ForeignKey(blank=True, db_column='sample_type_id', db_comment='Type of the sample from which the isolate was obtained', null=True, on_delete=django.db.models.deletion.PROTECT, to='home.sampletype', verbose_name='Sample type'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='invitro_serotype',
            field=models.ForeignKey(blank=True, db_column='invitro_serotype_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='home.invitroserotype', verbose_name='In vitro serotype'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='isolate_id',
            field=models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='home.metadatageneral'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='mic',
            field=models.ForeignKey(blank=True, db_column='mic_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='home.mic'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='collection_ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', db_comment='Name of the departament where the isolate was obtained', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='home.ward', verbose_name='Ward'),
        ),
    ]
