# Generated by Django 4.2.25 on 2026-05-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ward_remove_mic_ptz_remove_mic_ptz_clinical_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenotypicdata',
            name='morphotype',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Mucoid', 'Mucoid'), ('Small colony variant', 'Small colony variant')], db_comment='Morphotype of the isolate', max_length=30, null=True, verbose_name='Morphotype'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ami_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a amikacina', help_text='AMI-ARO:0000013 clinical category', max_length=3, null=True, verbose_name='Amikacin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='atm_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a aztreonam', help_text='AZT-ARO:3000550 clinical category', max_length=3, null=True, verbose_name='Aztreonam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='avi_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a avibactam', help_text='AVI-ARO:3000588 clinical category', max_length=3, null=True, verbose_name='Avibactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='azt_avi_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a aztreonam/avibactam', help_text='AZT/AVI-ARO:3007366 clinical category', max_length=3, null=True, verbose_name='Aztreonam/Avibactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz_avi_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftazidima/avibactam', help_text='CAZ/AVI-ARO:3007072 clinical category', max_length=3, null=True, verbose_name='Ceftazidime/Avibactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftazidima', help_text='CAZ-ARO:0000060 clinical category', max_length=3, null=True, verbose_name='Ceftazidime clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cfdc_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefiderocol', help_text='FDC-ARO:3004474 clinical category', max_length=3, null=True, verbose_name='Cefiderocol clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cip_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ciprofloxacino', help_text='CIP-ARO:0000036 clinical category', max_length=3, null=True, verbose_name='Ciprofloxacin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='col_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a colistina', help_text='COL-ARO:0000067 clinical category', max_length=3, null=True, verbose_name='Colistin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ctz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftolozano', help_text='TOL/TZ-ARO:3004724 clinical category', max_length=3, null=True, verbose_name='Ceftolozane/Tazobactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='dlx_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a delafloxacino', help_text='DLX-ARO:3004462 clinical category', max_length=3, null=True, verbose_name='Delafloxacin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='dur_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a durlobactam', help_text='DUR-ARO:3007293 clinical category', max_length=3, null=True, verbose_name='Durlobactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fdc_xer_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefiderocol/xeruborbactam', help_text='FDC_XER-ARO:???????? clinical category', max_length=3, null=True, verbose_name='Cefiderocol/Xeruborbactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fep_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefepima', help_text='FEP-ARO:0000059 clinical category', max_length=3, null=True, verbose_name='Cefepime clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fep_tan_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefepime/taniborbactam', help_text='FEP_TAN-ARO:3007148 clinical category', max_length=3, null=True, verbose_name='Cefepime/Taniborbactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fep_zid_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefepime/zidebactam', help_text='FEP_ZID-ARO:??????? clinical category', max_length=3, null=True, verbose_name='Cefepime/Zidebactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fo_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a fosfomicina', help_text='FOS-ARO:0000025 clinical category', max_length=3, null=True, verbose_name='Fosfomycin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='gen_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a gentamicina', help_text='GEN-ARO:3007382 clinical category', max_length=3, null=True, verbose_name='Gentamycin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a imipenem', help_text='IMI-ARO:3000170 clinical category', max_length=3, null=True, verbose_name='Imipenem clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi_rel_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a imipenem/relebactam', help_text='IMI/REL-ARO:???????? clinical category', max_length=3, null=True, verbose_name='Imipenem/Relebactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='lvx_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a levofloxacino', help_text='LVX-ARO:0000071 clinical category', max_length=3, null=True, verbose_name='Levofloxacin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem', help_text='MER-ARO:0000073 clinical category', max_length=3, null=True, verbose_name='Meropenem clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer_nac_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem/nacubactam', help_text='MER_NAC-ARO:???????? clinical category', max_length=3, null=True, verbose_name='Meropenem/Nacubactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer_vab_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem/vaborbactam', help_text='MER/VAB-ARO:3007146 clinical category', max_length=3, null=True, verbose_name='Meropenem/Vaborbactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer_xer_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem/xeruborbactam', help_text='MER_XER-ARO:???????? clinical category', max_length=3, null=True, verbose_name='Meropenem/Xeruborbactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mxl_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a moxifloxacino', help_text='MXL-ARO:0000074 clinical category', max_length=3, null=True, verbose_name='Moxifloxacin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='nac_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a nacubactam', help_text='NAC-ARO:3007295 clinical category', max_length=3, null=True, verbose_name='Nacubactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='net_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a netilmicina', help_text='NET-ARO:0000038 clinical category', max_length=3, null=True, verbose_name='Netilmycin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a piperacilina', help_text='PIP-ARO:0000078 clinical category', max_length=3, null=True, verbose_name='Piperacillin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip_tz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a piperacilina/tazobactam', help_text='PIP/TZ-ARO:3004021 clinical category', max_length=3, null=True, verbose_name='Piperacillin/Tazobactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='rel_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a relebactam', help_text='REL-ARO:3007031 clinical category', max_length=3, null=True, verbose_name='Relebactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='taz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tazobactam', help_text='TZ-ARO:0000077 clinical category', max_length=3, null=True, verbose_name='Tazobactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tic_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ticarcilina', help_text='TIC-ARO:3003832 clinical category', max_length=3, null=True, verbose_name='Ticarcillin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tob_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tobramicina', help_text='TOB-ARO:0000052 clinical category', max_length=3, null=True, verbose_name='Tobramycin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tol_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tebipenem pivoxil', help_text='TOL-ARO:3003927 clinical category', max_length=3, null=True, verbose_name='Ceftolozane clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='xer_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a xeruborbactam', help_text='XER-ARO:3007048 clinical category', max_length=3, null=True, verbose_name='Xeruborbactam clinical category'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='dtr_profile',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], db_comment='Difficult-to-treat resistance profile', max_length=3, null=True, verbose_name='Difficult-to-treat profile'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_name_en',
            field=models.CharField(blank=True, db_comment='Name of the ward in english where the isolate was obtained', max_length=255, null=True, verbose_name='Ward name in english'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_name_es',
            field=models.CharField(blank=True, db_comment='Name of the ward in spanish where the isolate was obtained', max_length=255, null=True, verbose_name='Ward name in spanish'),
        ),
    ]
