# Generated by Django 4.2.24 on 2025-10-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_interestgenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestgenes',
            name='official_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interestgenes',
            name='pbp_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interestgenes',
            name='synonym_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
