# Generated by Django 4.2.24 on 2025-10-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_interestgenes_official_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestgenes',
            name='allele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
