# Generated by Django 4.2.13 on 2024-06-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phenotypicdata',
            options={'managed': True, 'verbose_name_plural': 'Phenotypic Data'},
        ),
        migrations.AddField(
            model_name='phenotypicdata',
            name='Phenotypic_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
