# Generated by Django 4.2.25 on 2025-10-16 11:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_interestgenes_allele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestgenes',
            name='allele',
            field=models.CharField(blank=True, db_comment='Allele and (strain reference)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interestgenes',
            name='subset',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BASIC', 'Basic resistome'), ('CR', 'Cefiderocol resistance'), ('MLST', 'Locus for MLST identification'), ('-', 'N/A'), ('OT', 'Other')], max_length=100, null=True),
        ),
    ]
