# Generated by Django 4.2.13 on 2024-06-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_phenotypicdata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phenotypicdata',
            old_name='Phenotypic_comments',
            new_name='phenotypic_comments',
        ),
    ]
