# Generated by Django 4.2.13 on 2024-07-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_phenotypic_comments_phenotypicdata_phenotypic_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenceanalysis',
            name='ame_loci',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sequenceanalysis',
            name='beta_lactamase_loci',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sequenceanalysis',
            name='carbapenemase_loci',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sequenceanalysis',
            name='other_acq_ab_loci',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
