# Generated by Django 4.2.25 on 2025-10-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_interestgenes_allele_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestgenes',
            name='reference_strain',
            field=models.CharField(blank=True, choices=[('PAO1_GCF_000006765.1', 'GCF_000006765.1'), ('PA14_GCF_000014625.1', 'GCF_000014625.1'), ('-', 'N/A'), ('OT', 'Other')], max_length=100, null=True),
        ),
    ]
