# Generated by Django 4.2.13 on 2024-07-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sequenceanalysis_ame_loci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataclinic',
            name='isolate_id',
        ),
        migrations.AddField(
            model_name='metadataclinic',
            name='isolate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código hospital'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios hospital'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre hospital'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolate_comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios aislado'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolate_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre aislado'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolate_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Origen aislado'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha aislado'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre proyecto'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='species',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='ab_susceptibility_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Test susceptibilidad antibiótica'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='class_a_carbapenemase_test',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Test Carbapenemasas clase A'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='cloxa_test',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Test cloxa'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='ecdc_resistance_profile',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Perfil ECDC'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='esbl_test',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Test esbl'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='hypermutator_phenotype',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Fenotipo hipermutador'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='idsa_resistance_profile',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Perfil IDSA'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='invitro_serotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.invitroserotype', verbose_name='Serotipo in vitro'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='mbl_test',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Test mbl'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='phenotypic_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios fenotipo'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='ame_loci',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Loci EMA'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='beta_lactamase_loci',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Loci beta lactamasas'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='carbapenemase_loci',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Loci carbapeneasas'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='clonal_complex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Complejo clonal'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='insilico_serotype',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Serotipo in silico'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='mlst_allelic_profile',
            field=models.JSONField(blank=True, null=True, verbose_name='Perfil alélico MLST'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='other_acq_ab_loci',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Loci otros AB adquiridos'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='sequence_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de secuencia'),
        ),
    ]
