# Generated by Django 4.2.25 on 2026-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_interestgenes_reference_strain'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepath',
            name='denovo_assembly_ena_url',
            field=models.CharField(blank=True, db_comment='Path to the endpoint in ENA database where assembly file of the isolate is stored', max_length=255, null=True, verbose_name='ENA de novo file url'),
        ),
        migrations.AddField(
            model_name='filepath',
            name='fastq_files_names',
            field=models.JSONField(blank=True, db_comment='Name of the FASTQ files of the isolate, separated by comma if more than one', null=True, verbose_name='FASTQ file/s name/s'),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='denovo_assembly_path',
            field=models.CharField(blank=True, db_comment='Path to the folder where de novo files of the isolate are stored', max_length=255, null=True, verbose_name='De novo files path'),
        ),
        migrations.AlterField(
            model_name='interestgenes',
            name='reference_strain',
            field=models.CharField(blank=True, choices=[('GCF_000006765.1', 'PAO1_GCF_000006765.1'), ('GCF_000014625.1', 'PA14_GCF_000014625.1'), ('-', 'N/A'), ('OT', 'Other')], max_length=100, null=True),
        ),
    ]
