# Generated by Django 4.2.25 on 2026-03-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_filepath_denovo_assembly_ena_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepath',
            name='denovo_fastq_ena_url',
            field=models.JSONField(blank=True, db_comment='JSON with paths to endpoints in ENA database where FASTQ files of the isolate are stored', null=True, verbose_name='ENA FASTQ url'),
        ),
    ]
