# Generated by Django 4.2.13 on 2024-07-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_metadataclinic_isolate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadataclinic',
            old_name='isolate',
            new_name='isolate_id',
        ),
    ]
