# Generated by Django 4.2.25 on 2026-03-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_filepath_denovo_fastq_ena_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepath',
            name='ena_accession',
            field=models.CharField(blank=True, db_comment='Accession number of the isolate in ENA database', max_length=100, null=True, verbose_name='ENA accession number'),
        ),
    ]
