# Generated by Django 4.2.13 on 2024-07-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_isolate_metadataclinic_isolate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepath',
            old_name='isolate',
            new_name='isolate_id',
        ),
        migrations.RenameField(
            model_name='mic',
            old_name='isolate',
            new_name='isolate_id',
        ),
        migrations.RenameField(
            model_name='phenotypicdata',
            old_name='isolate',
            new_name='isolate_id',
        ),
        migrations.RenameField(
            model_name='sequenceanalysis',
            old_name='isolate',
            new_name='isolate_id',
        ),
        migrations.RenameField(
            model_name='sequencinginfo',
            old_name='isolate',
            new_name='isolate_id',
        ),
    ]
