# Generated by Django 4.2.13 on 2024-07-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_isolate_filepath_isolate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataclinic',
            name='sample_type',
            field=models.ForeignKey(blank=True, db_column='sample_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sampletype'),
        ),
    ]
