# Generated by Django 4.2.14 on 2024-08-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_metadataclinic_sample_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepath',
            name='isolate_id',
            field=models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='isolate_id',
            field=models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='isolate_id',
            field=models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='isolate_id',
            field=models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='isolate_id',
            field=models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral'),
        ),
        migrations.AlterField(
            model_name='sequencinginfo',
            name='isolate_id',
            field=models.OneToOneField(blank=True, db_column='isolate_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.metadatageneral'),
        ),
    ]
