# Generated by Django 4.2.15 on 2024-09-02 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_filepath_isolate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='geo_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='geo_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='collection_ward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento donde se obtuvo'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='hospital',
            field=models.ForeignKey(blank=True, db_column='hospital', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospitals', to='home.hospital'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='sample_type',
            field=models.ForeignKey(blank=True, db_column='sample_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sampletype', verbose_name='Tipo de muestra'),
        ),
        migrations.AlterField(
            model_name='sampletype',
            name='sample',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de muestra'),
        ),
        migrations.AlterField(
            model_name='sampletype',
            name='sample_type_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Tipo de muestra'),
        ),
    ]
