# Generated by Django 4.2.15 on 2024-10-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_hospital_geo_latitude_hospital_geo_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_ccn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código CCN hospital'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_codcnh',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código CODCNH hospital'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sub_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.AutoField(db_column='hospital_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comunidad autónoma'),
        ),
    ]
