# Generated by Django 4.2.16 on 2025-01-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_hospital_hospital_ccn_hospital_hospital_codcnh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mic',
            old_name='ct',
            new_name='ctz',
        ),
        migrations.RenameField(
            model_name='mic',
            old_name='ct_clinical_category',
            new_name='ctz_clinical_category',
        ),
    ]
