# Generated by Django 4.2.16 on 2025-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_ct_mic_ctz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakpointTable',
            fields=[
                ('breakpoint_table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_version_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tabla Puntos de corte')),
                ('table_version_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Versíón de tabla')),
                ('valid_date', models.DateTimeField(verbose_name='Fecha inicio de validez')),
                ('organism', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organismo')),
                ('organization', models.CharField(blank=True, max_length=50, null=True, verbose_name='Organización')),
                ('filepath', models.FilePathField(blank=True, max_length=255, null=True)),
                ('mic_breakpoints', models.JSONField(blank=True, null=True)),
                ('zd_breakpoints', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'breakpoint',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='mic',
            name='ami',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Amikacina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='atm',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Aztreonam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='azt',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Aztreonam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='azt_avi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Aztreonam/Avibactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ceftazidima'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz_avi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ceftazidima/Avibactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cfdc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cefiderocol'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ciprofloxacino'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='col',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Colistina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ctz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ceftolozano'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cza',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ceftazidima/Avibactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='dlx',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Delafloxacino'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cefepima'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fosfomicina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='gen',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Gentamicina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Imipenem'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi_rel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Imipenem/Relebactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='lvx',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Levofloxacino'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Meropenem'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer_vab',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Meropenem/Vaborbactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mxl',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Moxifloxacino'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='net',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Netilmicina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Piperacilina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip_tz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Piperacilina/Tazobactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ptz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Piperacilina/Tazobactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='taz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tazobactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tic',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ticarcilina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tob',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tobramicina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tol',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tebipenem pivoxil'),
        ),
    ]
