# Generated by Django 4.2.16 on 2025-02-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_breakpointtable_alter_mic_ami_alter_mic_atm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadataclinic',
            old_name='patient_id',
            new_name='patient_code',
        ),
        migrations.RemoveField(
            model_name='metadataclinic',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='metadatageneral',
            name='isolate_project_id',
        ),
        migrations.AddField(
            model_name='metadataclinic',
            name='hospital_id',
            field=models.ForeignKey(blank=True, db_column='hospital_id', db_comment='Hospital donde se obtuvo el aislado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospitals', to='home.hospital'),
        ),
        migrations.AddField(
            model_name='metadatageneral',
            name='isolate_project_code',
            field=models.CharField(blank=True, db_comment='código del proyecto', max_length=50, null=True, unique=True, verbose_name='Código proyecto'),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='assembler',
            field=models.ForeignKey(blank=True, db_column='assembler_id', db_comment='Ensamblador utilizado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.assembler'),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='denovo_assembly_path',
            field=models.CharField(blank=True, db_comment='Ruta de ubicación de los archivos de ensamblaje denovo del aislado', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='fastq_path',
            field=models.CharField(blank=True, db_comment='Ruta de ubicación de los archivos fastq del aislado', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='collection_ward',
            field=models.CharField(blank=True, db_comment='Departamento del hospital donde se obtuvo el aislado', max_length=255, null=True, verbose_name='Departamento donde se obtuvo'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='sample_type',
            field=models.ForeignKey(blank=True, db_column='sample_type_id', db_comment='Tipo de muestra del que se obtuvo el aislado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sampletype', verbose_name='Tipo de muestra'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolate_comments',
            field=models.CharField(blank=True, db_comment='Comentarios sobre el aislado', max_length=255, null=True, verbose_name='Comentarios aislado'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolate_name',
            field=models.CharField(blank=True, db_comment='Nombre del aislado', max_length=50, null=True, verbose_name='Nombre aislado'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolate_source',
            field=models.CharField(blank=True, db_comment='Origen clínico del aislado', max_length=255, null=True, verbose_name='Origen aislado'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_date',
            field=models.DateField(blank=True, db_comment='Fecha completa de obtención del aislado', null=True, verbose_name='Fecha aislado'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_day',
            field=models.IntegerField(blank=True, db_comment='Día de obtención del aislado', null=True),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_month',
            field=models.IntegerField(blank=True, db_comment='Mes de obtención del aislado', null=True),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_year',
            field=models.IntegerField(blank=True, db_comment='Año de obtención del aislado', null=True),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='project_name',
            field=models.CharField(blank=True, db_comment='Nombre del proyecto', max_length=255, null=True, verbose_name='Nombre proyecto'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='species',
            field=models.CharField(blank=True, db_comment='Especie del aislado', max_length=255, null=True, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ami',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de amikacina', max_length=10, null=True, verbose_name='Amikacina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ami_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a amikacina', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='atm',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de aztreonam', max_length=10, null=True, verbose_name='Aztreonam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='atm_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a aztreonam', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='azt',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de aztreonam', max_length=10, null=True, verbose_name='Aztreonam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='azt_avi',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de aztreonam/avibactam', max_length=10, null=True, verbose_name='Aztreonam/Avibactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='azt_avi_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a aztreonam/avibactam', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='azt_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a aztreonam', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftazidima', max_length=10, null=True, verbose_name='Ceftazidima'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz_avi',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftazidima/avibactam', max_length=10, null=True, verbose_name='Ceftazidima/Avibactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz_avi_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftazidima/avibactam', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftazidima', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz_cloxa',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftazidima/cloxacilina', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cfdc',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de cefiderocol', max_length=10, null=True, verbose_name='Cefiderocol'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cfdc_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefiderocol', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cip',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ciprofloxacino', max_length=10, null=True, verbose_name='Ciprofloxacino'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cip_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ciprofloxacino', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='col',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de colistina', max_length=10, null=True, verbose_name='Colistina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='col_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a colistina', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ctz',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftolozano', max_length=10, null=True, verbose_name='Ceftolozano'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ctz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftolozano', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cza',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftazidima/avibactam', max_length=10, null=True, verbose_name='Ceftazidima/Avibactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cza_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftazidima/avibactam', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='dlx',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de delafloxacino', max_length=10, null=True, verbose_name='Delafloxacino'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='dlx_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a delafloxacino', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fep',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de cefepima', max_length=10, null=True, verbose_name='Cefepima'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fep_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefepima', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fo',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de fosfomicina', max_length=10, null=True, verbose_name='Fosfomicina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fo_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a fosfomicina', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='gen',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de gentamicina', max_length=10, null=True, verbose_name='Gentamicina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='gen_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a gentamicina', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de imipenem', max_length=10, null=True, verbose_name='Imipenem'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a imipenem', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi_cloxa',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de imipenem/cloxacilina', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi_rel',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de imipenem/relebactam', max_length=10, null=True, verbose_name='Imipenem/Relebactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi_rel_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a imipenem/relebactam', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='lvx',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de levofloxacino', max_length=10, null=True, verbose_name='Levofloxacino'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='lvx_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a levofloxacino', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de meropenem', max_length=10, null=True, verbose_name='Meropenem'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer_vab',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de meropenem/vaborbactam', max_length=10, null=True, verbose_name='Meropenem/Vaborbactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer_vab_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem/vaborbactam', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mic_comments',
            field=models.CharField(blank=True, db_comment='Comentarios de la concentración mínima inhibitoria', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mxl',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de moxifloxacino', max_length=10, null=True, verbose_name='Moxifloxacino'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mxl_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a moxifloxacino', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='net',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de netilmicina', max_length=10, null=True, verbose_name='Netilmicina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='net_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a netilmicina', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de piperacilina', max_length=10, null=True, verbose_name='Piperacilina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a piperacilina', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip_tz',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de piperacilina/tazobactam', max_length=10, null=True, verbose_name='Piperacilina/Tazobactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip_tz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a piperacilina/tazobactam', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ptz',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de piperacilina/tazobactam', max_length=10, null=True, verbose_name='Piperacilina/Tazobactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ptz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a piperacilina/tazobactam', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='taz',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de tazobactam', max_length=10, null=True, verbose_name='Tazobactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='taz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tazobactam', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tic',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ticarcilina', max_length=10, null=True, verbose_name='Ticarcilina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tic_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ticarcilina', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tob',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de tobramicina', max_length=10, null=True, verbose_name='Tobramicina'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tob_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tobramicina', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tol',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de tebipenem pivoxil', max_length=10, null=True, verbose_name='Tebipenem pivoxil'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tol_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tebipenem pivoxil', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='ab_susceptibility_method',
            field=models.CharField(blank=True, db_comment='Método utilizado para determinar la susceptibilidad antibiótica', max_length=100, null=True, verbose_name='Test susceptibilidad antibiótica'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='class_a_carbapenemase_test',
            field=models.CharField(blank=True, db_comment='Valor del test de carbapenemasas clase A', max_length=3, null=True, verbose_name='Test Carbapenemasas clase A'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='cloxa_test',
            field=models.CharField(blank=True, db_comment='Valor del test cloxa de ceftazidima, valores: +/-', max_length=3, null=True, verbose_name='Test cloxa'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='ecdc_resistance_profile',
            field=models.CharField(blank=True, db_comment='Perfil de resistencia según ECDC', max_length=3, null=True, verbose_name='Perfil ECDC'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='esbl_test',
            field=models.CharField(blank=True, db_comment='Valor del test esbl, valores: +/-', max_length=3, null=True, verbose_name='Test esbl'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='hypermutator_phenotype',
            field=models.CharField(blank=True, db_comment='Fenotipo hipermutador', max_length=15, null=True, verbose_name='Fenotipo hipermutador'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='idsa_resistance_profile',
            field=models.CharField(blank=True, db_comment='Perfil de resistencia según IDSA', max_length=3, null=True, verbose_name='Perfil IDSA'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='invitro_serotype',
            field=models.ForeignKey(blank=True, db_column='invitro_serotype_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.invitroserotype', verbose_name='Serotipo in vitro'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='mbl_test',
            field=models.CharField(blank=True, db_comment='Valor del test mbl, valores: +/-', max_length=3, null=True, verbose_name='Test mbl'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='mic',
            field=models.ForeignKey(blank=True, db_column='mic_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.mic'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='phenotypic_comments',
            field=models.TextField(blank=True, db_comment='Comentarios sobre el fenotipo del aislado', null=True, verbose_name='Comentarios fenotipo'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='acquired_resistome',
            field=models.JSONField(blank=True, db_comment='Resistoma adquirido en formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='ame_loci',
            field=models.CharField(blank=True, db_comment='Loci de enzimas de modificación de aminoglucósidos, listado de nombres separados por comas', max_length=500, null=True, verbose_name='Loci EMA'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='beta_lactamase_loci',
            field=models.CharField(blank=True, db_comment='Loci de beta-lactamasas, listado de nombres separados por comas', max_length=500, null=True, verbose_name='Loci beta lactamasas'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='betalactamase_pcr',
            field=models.JSONField(blank=True, db_comment='Resultados de PCR de beta-lactamasas en formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='carbapenemase_loci',
            field=models.CharField(blank=True, db_comment='Loci de carbapenemasas, listado de nombres separados por comas', max_length=500, null=True, verbose_name='Loci carbapeneasas'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='clonal_complex',
            field=models.CharField(blank=True, db_comment='Complejo clonal del aislado', max_length=10, null=True, verbose_name='Complejo clonal'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='hypermutation_genes',
            field=models.JSONField(blank=True, db_comment='Genes de hipermutación en formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='insilico_serotype',
            field=models.CharField(blank=True, db_comment='Serotipo in silico del aislado', max_length=3, null=True, verbose_name='Serotipo in silico'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='mlst_allelic_profile',
            field=models.JSONField(blank=True, db_comment='Perfil alélico de MLST en formato JSON', null=True, verbose_name='Perfil alélico MLST'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='mutational_resistome',
            field=models.JSONField(blank=True, db_comment='Resistoma mutacional en formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='other_acq_ab_loci',
            field=models.CharField(blank=True, db_comment='Loci de otros genes de resistencia adquiridos, listado de nombres separados por comas', max_length=500, null=True, verbose_name='Loci otros AB adquiridos'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='sequence_type',
            field=models.CharField(blank=True, db_comment='ST del aislado', max_length=10, null=True, verbose_name='Tipo de secuencia'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='virulence_genes',
            field=models.JSONField(blank=True, db_comment='Genes de virulencia en formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='sequencinginfo',
            name='flowcell_kit',
            field=models.ForeignKey(blank=True, db_column='flowcell_kit_id', db_comment='Flowcell Kit utilizado en la secuenciación', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.flowcellkit'),
        ),
        migrations.AlterField(
            model_name='sequencinginfo',
            name='library_method',
            field=models.ForeignKey(blank=True, db_column='library_method_id', db_comment='Método de preparación de la librería', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sequencinglibrary'),
        ),
        migrations.AlterField(
            model_name='sequencinginfo',
            name='sequencing_goal',
            field=models.CharField(blank=True, db_comment='Objetivo de la secuenciación, cual es el motivo para el que se realiza la secuenciación', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sequencinginfo',
            name='sequencing_platform',
            field=models.ForeignKey(blank=True, db_column='sequencing_platform_id', db_comment='Plataforma de secuenciación para obtener el aislado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sequencingplatform'),
        ),
        migrations.AlterField(
            model_name='sequencinginfo',
            name='sequencing_source',
            field=models.CharField(blank=True, db_comment='Fuente de la secuenciación, de donde se obtuvo la secuencia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sequencinginfo',
            name='sequencing_technology',
            field=models.ForeignKey(blank=True, db_column='sequencing_technology_id', db_comment='Tecnología de secuenciación para obtener el aislado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sequencingtechnology'),
        ),
    ]
