# Generated by Django 4.2.19 on 2025-02-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_patient_id_metadataclinic_patient_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepath',
            name='assembler',
            field=models.ForeignKey(blank=True, db_column='assembler_id', db_comment='Ensamblador utilizado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.assembler'),
        ),
    ]
