# Generated by Django 4.2.19 on 2025-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_filepath_assembler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mic',
            options={'managed': True, 'verbose_name': 'MIC'},
        ),
        migrations.RemoveField(
            model_name='mic',
            name='azt',
        ),
        migrations.RemoveField(
            model_name='mic',
            name='azt_clinical_category',
        ),
        migrations.RemoveField(
            model_name='mic',
            name='cza',
        ),
        migrations.RemoveField(
            model_name='mic',
            name='cza_clinical_category',
        ),
        migrations.AlterField(
            model_name='mic',
            name='ami',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de amikacina', help_text='AMI-ARO:0000013', max_length=10, null=True, verbose_name='Amikacin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ami_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a amikacina', help_text='AMI-ARO:0000013 clinical category', max_length=2, null=True, verbose_name='Amikacin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='atm',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de aztreonam', help_text='AZT-ARO:3000550', max_length=10, null=True, verbose_name='Aztreonam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='atm_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a aztreonam', help_text='AZT-ARO:3000550 clinical category', max_length=2, null=True, verbose_name='Aztreonam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='azt_avi',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de aztreonam/avibactam', help_text='AZT/AVI-ARO:3007366', max_length=10, null=True, verbose_name='Aztreonam/Avibactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='azt_avi_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a aztreonam/avibactam', help_text='AZT/AVI-ARO:3007366 clinical category', max_length=2, null=True, verbose_name='Aztreonam/Avibactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftazidima', help_text='CAZ-ARO:0000060', max_length=10, null=True, verbose_name='Ceftazidime'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz_avi',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftazidima/avibactam', help_text='CAZ/AVI-ARO:3007072', max_length=10, null=True, verbose_name='Ceftazidime/Avibactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz_avi_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftazidima/avibactam', help_text='CAZ/AVI-ARO:3007072 clinical category', max_length=2, null=True, verbose_name='Ceftazidime/Avibactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='caz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftazidima', help_text='CAZ-ARO:0000060 clinical category', max_length=2, null=True, verbose_name='Ceftazidime clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cfdc',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de cefiderocol', help_text='FDC-ARO:3004474', max_length=10, null=True, verbose_name='Cefiderocol'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cfdc_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefiderocol', help_text='FDC-ARO:3004474 clinical category', max_length=2, null=True, verbose_name='Cefiderocol clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cip',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ciprofloxacino', help_text='CIP-ARO:0000036', max_length=10, null=True, verbose_name='Ciprofloxacin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='cip_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ciprofloxacino', help_text='CIP-ARO:0000036 clinical category', max_length=2, null=True, verbose_name='Ciprofloxacin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='col',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de colistina', help_text='COL-ARO:0000067', max_length=10, null=True, verbose_name='Colistin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='col_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a colistina', help_text='COL-ARO:0000067 clinical category', max_length=2, null=True, verbose_name='Colistin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ctz',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftolozano/tazobactam', help_text='TOL/TZ-ARO:3004724', max_length=10, null=True, verbose_name='Ceftolozane/Tazobactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ctz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ceftolozano', help_text='TOL/TZ-ARO:3004724 clinical category', max_length=2, null=True, verbose_name='Ceftolozane/Tazobactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='dlx',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de delafloxacino', help_text='DLX-ARO:3004462', max_length=10, null=True, verbose_name='Delafloxacin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='dlx_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a delafloxacino', help_text='DLX-ARO:3004462 clinical category', max_length=2, null=True, verbose_name='Delafloxacin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fep',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de cefepima', help_text='FEP-ARO:0000059', max_length=10, null=True, verbose_name='Cefepime'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fep_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a cefepima', help_text='FEP-ARO:0000059 clinical category', max_length=2, null=True, verbose_name='Cefepime clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fo',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de fosfomicina', help_text='FOS-ARO:0000025', max_length=10, null=True, verbose_name='Fosfomycin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='fo_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a fosfomicina', help_text='FOS-ARO:0000025 clinical category', max_length=2, null=True, verbose_name='Fosfomycin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='gen',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de gentamicina', help_text='GEN-ARO:3007382', max_length=10, null=True, verbose_name='Gentamycin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='gen_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a gentamicina', help_text='GEN-ARO:3007382 clinical category', max_length=2, null=True, verbose_name='Gentamycin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de imipenem', help_text='IMI-ARO:3000170', max_length=10, null=True, verbose_name='Imipenem'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a imipenem', help_text='IMI-ARO:3000170 clinical category', max_length=2, null=True, verbose_name='Imipenem clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi_rel',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de imipenem/relebactam', help_text='IMI/REL-ARO:????????', max_length=10, null=True, verbose_name='Imipenem/Relebactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='imi_rel_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a imipenem/relebactam', help_text='IMI/REL-ARO:???????? clinical category', max_length=2, null=True, verbose_name='Imipenem/Relebactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='lvx',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de levofloxacino', help_text='LVX-ARO:0000071', max_length=10, null=True, verbose_name='Levofloxacin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='lvx_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a levofloxacino', help_text='LVX-ARO:0000071 clinical category', max_length=2, null=True, verbose_name='Levofloxacin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de meropenem', help_text='MER-ARO:0000073', max_length=10, null=True, verbose_name='Meropenem'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem', help_text='MER-ARO:0000073 clinical category', max_length=2, null=True, verbose_name='Meropenem clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer_vab',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de meropenem/vaborbactam', help_text='MER/VAB-ARO:3007146', max_length=10, null=True, verbose_name='Meropenem/Vaborbactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mer_vab_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a meropenem/vaborbactam', help_text='MER/VAB-ARO:3007146 clinical category', max_length=2, null=True, verbose_name='Meropenem/Vaborbactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mic_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='MIC_id'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mxl',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de moxifloxacino', help_text='MXL-ARO:0000074', max_length=10, null=True, verbose_name='Moxifloxacin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='mxl_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a moxifloxacino', help_text='MXL-ARO:0000074 clinical category', max_length=2, null=True, verbose_name='Moxifloxacin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='net',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de netilmicina', help_text='NET-ARO:0000038', max_length=10, null=True, verbose_name='Netilmycin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='net_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a netilmicina', help_text='NET-ARO:0000038 clinical category', max_length=2, null=True, verbose_name='Netilmycin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de piperacilina', help_text='PIP-ARO:0000078', max_length=10, null=True, verbose_name='Piperacillin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a piperacilina', help_text='PIP-ARO:0000078 clinical category', max_length=2, null=True, verbose_name='Piperacillin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip_tz',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de piperacilina/tazobactam', help_text='PIP/TZ-ARO:3004021', max_length=10, null=True, verbose_name='Piperacillin/Tazobactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='pip_tz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a piperacilina/tazobactam', help_text='PIP/TZ-ARO:3004021 clinical category', max_length=2, null=True, verbose_name='Piperacillin/Tazobactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ptz',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de piperacilina/tazobactam', help_text='PIP/TZ-ARO:3004021', max_length=10, null=True, verbose_name='Piperacillin/Tazobactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='ptz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a piperacilina/tazobactam', help_text='PIP/TZ-ARO:3004021 clinical category', max_length=2, null=True, verbose_name='Piperacillin/Tazobactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='taz',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de tazobactam', help_text='TZ-ARO:0000077', max_length=10, null=True, verbose_name='Tazobactam'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='taz_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tazobactam', help_text='TZ-ARO:0000077 clinical category', max_length=2, null=True, verbose_name='Tazobactam clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tic',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ticarcilina', help_text='TIC-ARO:3003832', max_length=10, null=True, verbose_name='Ticarcillin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tic_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a ticarcilina', help_text='TIC-ARO:3003832 clinical category', max_length=2, null=True, verbose_name='Ticarcillin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tob',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de tobramicina', help_text='TOB-ARO:0000052', max_length=10, null=True, verbose_name='Tobramycin'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tob_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tobramicina', help_text='TOB-ARO:0000052 clinical category', max_length=2, null=True, verbose_name='Tobramycin clinical category'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tol',
            field=models.CharField(blank=True, db_comment='Valor numérico de la concentración mínima inhibitoria de ceftolozano', help_text='TOL-ARO:3003927', max_length=10, null=True, verbose_name='Ceftolozane'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='tol_clinical_category',
            field=models.CharField(blank=True, db_comment='Categoría clínica de resistencia del aislado a tebipenem pivoxil', help_text='TOL-ARO:3003927 clinical category', max_length=2, null=True, verbose_name='Ceftolozane clinical category'),
        ),
    ]
