# Generated by Django 4.2.19 on 2025-02-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_mic_options_remove_mic_azt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequenceanalysis',
            name='carbapenemase_loci',
        ),
        migrations.RemoveField(
            model_name='sequenceanalysis',
            name='other_acq_ab_loci',
        ),
        migrations.AddField(
            model_name='sequenceanalysis',
            name='fluoroquinolones_loci',
            field=models.CharField(blank=True, db_comment='Fluoroquinolones resistance determinants loci, name list comma-separated', max_length=500, null=True, verbose_name='Fluoroquinolones resistance determinants'),
        ),
        migrations.AddField(
            model_name='sequenceanalysis',
            name='other_acq_loci',
            field=models.CharField(blank=True, db_comment='Other acquired resistance determinants, name list comma-separated', max_length=500, null=True, verbose_name='Other acquired resistance determinants'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='collection_ward',
            field=models.CharField(blank=True, db_comment='Name of the departament where the isolate was obtained', max_length=255, null=True, verbose_name='Ward'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='hospital_id',
            field=models.ForeignKey(blank=True, db_column='hospital_id', db_comment='Name of the hospital where the isolate was obtained', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospitals', to='home.hospital', verbose_name='Hospital'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='sample_type',
            field=models.ForeignKey(blank=True, db_column='sample_type_id', db_comment='Type of the sample from which the isolate was obtained', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.sampletype', verbose_name='Sample type'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolate_comments',
            field=models.CharField(blank=True, db_comment='Comments about the isolate', max_length=255, null=True, verbose_name='Isolate comments'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolate_name',
            field=models.CharField(blank=True, db_comment='Isolate name in its project', max_length=50, null=True, verbose_name='Isolate name'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolate_project_code',
            field=models.CharField(blank=True, db_comment='Official project code', max_length=50, null=True, unique=True, verbose_name='Project code'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolate_source',
            field=models.CharField(blank=True, db_comment='Clinic origin of the isolate', max_length=255, null=True, verbose_name='Isolate origin'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_date',
            field=models.DateField(blank=True, db_comment='Whole date of obtention of the isolate', null=True, verbose_name='Isolate obtention date'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_day',
            field=models.IntegerField(blank=True, db_comment='Isolate obtention day', null=True),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_month',
            field=models.IntegerField(blank=True, db_comment='Isolate obtention month', null=True),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_year',
            field=models.IntegerField(blank=True, db_comment='Isolate obtention year', null=True),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='project_name',
            field=models.CharField(blank=True, db_comment='Internal name of the project', max_length=255, null=True, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='species',
            field=models.CharField(blank=True, db_comment='Isolate species', max_length=255, null=True, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='ab_susceptibility_method',
            field=models.CharField(blank=True, db_comment='Method used to determine antibiotic susceptibility', max_length=100, null=True, verbose_name='ATB susceptibility method'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='class_a_carbapenemase_test',
            field=models.CharField(blank=True, db_comment='Class A carbapenemases test result', max_length=3, null=True, verbose_name='Class A carbapenemases'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='cloxa_test',
            field=models.CharField(blank=True, db_comment='CLOXA test result, accepted values: +/-', max_length=3, null=True, verbose_name='CLOXA test'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='ecdc_resistance_profile',
            field=models.CharField(blank=True, db_comment='Resistance profile following ECDC guidelines', max_length=3, null=True, verbose_name='ECDC profile'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='esbl_test',
            field=models.CharField(blank=True, db_comment='ESBL test result, accepted values: +/-', max_length=3, null=True, verbose_name='ESBL test'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='hypermutator_phenotype',
            field=models.CharField(blank=True, db_comment='Hypermutator phenotype', max_length=15, null=True, verbose_name='Hypermutator phenotype'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='idsa_resistance_profile',
            field=models.CharField(blank=True, db_comment='Resistance profile following IDSA guidelines', max_length=3, null=True, verbose_name='IDSA profile'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='invitro_serotype',
            field=models.ForeignKey(blank=True, db_column='invitro_serotype_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.invitroserotype', verbose_name='In vitro serotype'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='mbl_test',
            field=models.CharField(blank=True, db_comment='MBL test result, accepted values: +/-', max_length=3, null=True, verbose_name='MBL test'),
        ),
        migrations.AlterField(
            model_name='phenotypicdata',
            name='phenotypic_comments',
            field=models.TextField(blank=True, db_comment='Comments about isolate phenotype characteristics', null=True, verbose_name='Phenotypic comments'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='acquired_resistome',
            field=models.JSONField(blank=True, db_comment='Acquired resistome, in JSON format', null=True),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='ame_loci',
            field=models.CharField(blank=True, db_comment='Aminoglycoside modifying enzymes loci, name list comma-separated', max_length=500, null=True, verbose_name='AME loci'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='beta_lactamase_loci',
            field=models.CharField(blank=True, db_comment='Beta-lactamases/Carbapenemases loci, name list comma-separated', max_length=500, null=True, verbose_name='Beta-lactamases/Carbapenemases loci'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='betalactamase_pcr',
            field=models.JSONField(blank=True, db_comment='Beta-lactamases PCR results, in JSON format', null=True),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='clonal_complex',
            field=models.CharField(blank=True, db_comment='Clonal complex of the isolate', max_length=10, null=True, verbose_name='Clonal complex'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='hypermutation_genes',
            field=models.JSONField(blank=True, db_comment='Hypermutation genes, in JSON format', null=True),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='insilico_serotype',
            field=models.CharField(blank=True, db_comment='Phenotypic in silico serotype of the isolate', max_length=3, null=True, verbose_name='In silico serotype'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='mlst_allelic_profile',
            field=models.JSONField(blank=True, db_comment='Allelic values of loci used in multilocus strain typing, using JSON format', null=True, verbose_name='MLST allelic profile'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='mutational_resistome',
            field=models.JSONField(blank=True, db_comment='Mutational resistome, using JSON format', null=True),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='sequence_type',
            field=models.CharField(blank=True, db_comment='Sequence type of the isolate', max_length=10, null=True, verbose_name='Sequence type'),
        ),
        migrations.AlterField(
            model_name='sequenceanalysis',
            name='virulence_genes',
            field=models.JSONField(blank=True, db_comment='Virulencia genes, in JSON format', null=True),
        ),
        migrations.AlterField(
            model_name='sequencinginfo',
            name='sequencing_goal',
            field=models.CharField(blank=True, db_comment='Objective for sequencing this isolate', max_length=100, null=True, verbose_name='Sequencing goal'),
        ),
        migrations.AlterField(
            model_name='sequencinginfo',
            name='sequencing_source',
            field=models.CharField(blank=True, db_comment='Where was the sequencing obtained', max_length=100, null=True, verbose_name='Sequencing source'),
        ),
    ]
