# Generated by Django 4.2.19 on 2025-02-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_sequenceanalysis_carbapenemase_loci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepath',
            name='denovo_assembly_path',
            field=models.CharField(blank=True, db_comment='Path to the folder where de novo files of the isolate are stored', max_length=255, null=True, verbose_name='DeNovo files path'),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='fastq_path',
            field=models.CharField(blank=True, db_comment='Path to the folder where FASTQ files of the isolate are stored', max_length=255, null=True, verbose_name='FASTQ path'),
        ),
        migrations.AlterField(
            model_name='metadataclinic',
            name='patient_code',
            field=models.CharField(blank=True, db_comment='Code of the patient in the project', max_length=255, null=True, verbose_name='Patient code'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_day',
            field=models.IntegerField(blank=True, db_comment='Isolate obtention day', null=True, verbose_name='Isolate obtention day'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_month',
            field=models.IntegerField(blank=True, db_comment='Isolate obtention month', null=True, verbose_name='Isolate obtention month'),
        ),
        migrations.AlterField(
            model_name='metadatageneral',
            name='isolation_year',
            field=models.IntegerField(blank=True, db_comment='Isolate obtention year', null=True, verbose_name='Isolate obtention year'),
        ),
    ]
