# Generated by Django 4.2.19 on 2025-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_filepath_denovo_assembly_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotypicdata',
            name='ab_susceptibility_method',
            field=models.CharField(blank=True, choices=[('DISC_DIFFUSION', 'Disc diffusion'), ('BROTH_MICRODILUTION', 'Broth microdilution'), ('E_TEST', 'E-test'), ('OTHER', 'Other')], db_comment='Method used to determine antibiotic susceptibility', max_length=100, null=True, verbose_name='ATB susceptibility method'),
        ),
    ]
